---
- name: Test Ansible Modules
  hosts: localhost
  gather_facts: False
  
  tasks:
  
  - name: Read all sheets within spreadsheet
    spreadsheet_to_facts:
      src: test_spreadsheet.xlsx

  - name: Read specific sheet within spreadsheet
    spreadsheet_to_facts:
      src: test_spreadsheet.xlsx
      sheets:
        - zones